### ISSUE TITLE
background color in element_markdown()

### ISSUE THREAD

**Issue by fmmattioni** [wilkelab/ggtext#27]
I would like to apply a background color to `axis.text` as it is applied in `axis.title` in the following example:

<details><summary>Expand example</summary>

``` r
library(ggplot2)
library(ggtext)

ggplot(mtcars, aes(disp, mpg)) + 
  geom_point() +
  labs(
    title = "<b>Fuel economy vs. engine displacement</b><br>
    <span style = 'font-size:10pt'>Lorem ipsum *dolor sit amet,*
    consectetur adipiscing elit, **sed do eiusmod tempor incididunt** ut
    labore et dolore magna aliqua. <span style = 'color:red;'>Ut enim
    ad minim veniam,</span> quis nostrud exercitation ullamco laboris nisi
    ut aliquip ex ea commodo consequat.</span>",
    x = "displacement (in<sup>3</sup>)",
    y = "Miles per gallon (mpg)<br><span style = 'font-size:8pt'>A measure of
    the car's fuel efficiency.</span>"
  ) +
  theme(
    plot.title.position = "plot",
    plot.title = element_textbox_simple(
      size = 13,
      lineheight = 1,
      padding = margin(5.5, 5.5, 5.5, 5.5),
      margin = margin(0, 0, 5.5, 0),
      fill = "cornsilk"
    ),
    axis.title.x = element_textbox_simple(
      width = NULL,
      padding = margin(4, 4, 4, 4),
      margin = margin(4, 0, 0, 0),
      linetype = 1,
      r = grid::unit(8, "pt"),
      fill = "azure1"
    ),
    axis.title.y = element_textbox_simple(
      hjust = 0,
      orientation = "left-rotated",
      minwidth = unit(1, "in"),
      maxwidth = unit(2, "in"),
      padding = margin(4, 4, 2, 4),
      margin = margin(0, 0, 2, 0),
      fill = "lightsteelblue1"
    )
  )
```

![](https://i.imgur.com/THCJtUW.png)

<sup>Created on 2020-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

I tried the following:

<details><summary>Expand reprex</summary>

``` r
library(ggplot2)
library(ggtext)
library(dplyr)

df <- iris %>% 
  as_tibble() %>% 
  select(Species, Sepal.Width) %>% 
  mutate(Species = formattable::color_tile("pink", "lightblue")(Species)) %>% 
  print()
#> # A tibble: 150 x 2
#>    Species                                                           Sepal.Width
#>    <chr>                                                                   <dbl>
#>  1 "<span style=\"display: block; padding: 0 4px; border-radius: 4p…         3.5
#>  2 "<span style=\"display: block; padding: 0 4px; border-radius: 4p…         3  
#>  3 "<span style=\"display: block; padding: 0 4px; border-radius: 4p…         3.2
#>  4 "<span style=\"display: block; padding: 0 4px; border-radius: 4p…         3.1
#>  5 "<span style=\"display: block; padding: 0 4px; border-radius: 4p…         3.6
#>  6 "<span style=\"display: block; padding: 0 4px; border-radius: 4p…         3.9
#>  7 "<span style=\"display: block; padding: 0 4px; border-radius: 4p…         3.4
#>  8 "<span style=\"display: block; padding: 0 4px; border-radius: 4p…         3.4
#>  9 "<span style=\"display: block; padding: 0 4px; border-radius: 4p…         2.9
#> 10 "<span style=\"display: block; padding: 0 4px; border-radius: 4p…         3.1
#> # … with 140 more rows

df %>% 
  ggplot(aes(Species, Sepal.Width)) +
  geom_boxplot() +
  theme(
    axis.text.x = element_markdown()
  )
```

![](https://i.imgur.com/KCrwI90.png)

<sup>Created on 2020-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

But nothing happens.. Is it possible to do somehow?

**Comment by clauswilke** [comment]
Sorry, no, this isn't currently supported. Maybe at some point in the future. Will require a complete rewrite of the rendering engine, though.

**Comment by fmmattioni** [comment]
Thanks for the quick reply! I will see if I can come up with a custom function.

**Comment by clauswilke** [comment]
Addressed in #53.

**Comment by fmmattioni** [comment]
Hi @clauswilke, I was taking a look at `sinab` now, and it looks so cool! Is it already possible to use this with `ggplot2`?

**Comment by clauswilke** [comment]
@fmmattioni With a bit of work, yes. I may add these instructions to the sinab web site:
https://stackoverflow.com/a/63929139/4975218

**Comment by fmmattioni** [comment]
Thank you! This is so incredible! I am really looking forward to the official release! Thank you for this!

**Comment by fmmattioni** [comment]
Hi @clauswilke, just a follow up on this question: it seems that this still does not work in `axis.text`, any thoughts?

reprex:

``` r
library(ggplot2)
library(dplyr)
library(glue)
library(rlang)
library(sinab)  # remotes::install_github("clauswilke/sinab")

# helper code that will eventually live in the ggtext package
element_html <- function(css = NULL, family = NULL, face = NULL, size = NULL, colour = NULL, fill = NULL,
                         linetype = NULL, linewidth = NULL, hjust = NULL, vjust = NULL, lineheight = NULL,
                         margin = NULL, width = NULL, height = NULL, color = NULL, 
                         debug = FALSE, inherit.blank = FALSE) {
  if (!is.null(color))
    colour <- color
  
  # doesn't work with other values at this time
  hjust <- 0
  vjust <- 1
  
  structure(
    list(
      css = css,
      family = family, face = face, size = size, colour = colour, fill = fill,
      linetype = linetype, linewidth = linewidth, hjust = hjust, vjust = vjust,
      lineheight = lineheight, margin = margin, width = width, height = height,
      debug = debug, inherit.blank = inherit.blank),
    class = c("element_html", "element_text", "element")
  )
}

element_grob.element_html <- function(element, label = "", x = NULL, y = NULL,
                                      family = NULL, face = NULL, colour = NULL, size = NULL,
                                      hjust = NULL, vjust = NULL, lineheight = NULL,
                                      margin = NULL, ...) {
  if (is.null(label))
    return(ggplot2::zeroGrob())
  
  # for now we ignore hjust and vjust, it doesn't work yet
  hj <- 0
  vj <- 1
  
  css <- element$css %||% ""
  
  html_grob(
    label, x = x, y = y, hjust = hj, vjust = vj,
    width = element$width, height = element$height,
    css = css
  )
}


# CSS styling
css <- '
p { text-align: center; padding-top: 2px; }
.setosa { text-align: left; }
'

# plotting code
iris %>%
  mutate(
    # set class attribute to species name
    Species = glue('<p class = "{Species}">{Species}</p>')
  ) %>%
  ggplot(aes(x = Petal.Width, y = Species)) +
  geom_boxplot() +
  theme(axis.text.y = element_html(css = css))
#> Error in valid.viewport(x, y, width, height, just, gp, clip, xscale, yscale, : 'x', 'y', 'width', and 'height' must all be units of length 1
```
<sup>Created on 2020-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
Yes, writing an element that can be used as axis text requires a little more work, because those elements need to be able to receive vectorized input. It's a solvable problem, but I don't have a solution ready to go at this time.

**Comment by fmmattioni** [comment]
Oh, I got it! Thank you!
